sudo: false
language: android
jdk:
- oraclejdk8

# Installs the newest platform tools instead of the outdated v23 travis has by default
android:
  components:
    # Below 3 lines are to download the newer android tools. Tools is listed twice on purpose. https://docs.travis-ci.com/user/languages/android/#installing-a-newer-sdk-platform-tools-revision
    - tools
    - platform-tools
    - tools
    # Other components needed for the build.
    - build-tools-28.0.2
    - android-28
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

install:
  - bundle install
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  bundler: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
notifications:
  email: false

jobs:
  include:
    - stage: danger
      script: bundle exec danger
    - stage: build
      script: ruby ./bin/ci/build.rb

stages:
  - name: danger
    if: type IN (pull_request)
  - name: build
    if: type IN (push, pull_request)
