package com.levibostian.teller.cachestate.listener

interface OnlineCacheStateListener<in CACHE>: OnlineCacheStateFetchingListener, OnlineCacheStateNoCacheStateListener, OnlineCacheStateCacheListener<CACHE>