name: Lint
# only run on PRs and when push a commit on a branch that we don't deploy on. 
on: [push, pull_request]

jobs:
  android-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [teller-android]
    name: Android Lint (${{ matrix.module }})
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11' # Robolectric requires v9, but we choose LTS: https://adoptopenjdk.net/
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Run lint (${{ matrix.module }})
      run: ./gradlew :${{ matrix.module }}:lintDebug || true

    - name: Parse lint results (${{ matrix.module }})
      uses: yutailang0119/action-android-lint@v1.0.2
      with:
        xml_path: ${{ matrix.module }}/build/reports/lint-results-debug.xml

  # Task to verify ktlint already ran for all commits. This verifies you have your git hooks installed. 
  kotlin-lint:
    runs-on: ubuntu-latest
    name: Kotlin Lint
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11' # Robolectric requires v9, but we choose LTS: https://adoptopenjdk.net/
    - name: Install ktlint
      uses: nbadal/action-ktlint-setup@v1
    - name: What version of ktlint are we using?
      run: ktlint --version 
    
    # The task will simply fail if it does not pass. It would be better if we make a comment on the PR telling the PR author to install git hooks but that scenario should not happen often (at least I don't think so) so for now, let's lean on assuming it will not happen and if it does happen a lot, we will improve this. 
    - name: Run ktlint
      run: ktlint --android "app/src/**/*.kt" "sdk/src/**/*.kt" 2> /dev/null 