name: Tests

on: [push, pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [teller-android]
    name: Unit tests (${{ matrix.module }})
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11' # Robolectric requires v9, but we choose LTS: https://adoptopenjdk.net/
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Run unit tests (${{ matrix.module }})
      # if test(s) fail, gradle will fail. We want the github action step to pass but let
      # our junit-reporter make a github action check failure if it finds failed tests. 
      run: ./gradlew :${{ matrix.module }}:testDebugUnitTest || true 

    - name: Publish test results (${{ matrix.module }})
      uses: mikepenz/action-junit-report@v2      
      with:
        report_paths: '**/build/test-results/test*/TEST-*.xml'
        require_tests: true 